### ISSUE TITLE
Certificate issue

### ISSUE THREAD

**Issue by IzzySoft** [AioFall/RhythmRoid#2]
A scan ([see here](https://gitlab.com/IzzyOnDroid/repo/-/issues/477) for details and background) just revealed the APKs at your releases are signed using a debug key. As that has security implications, may I ask you to please switch to a proper release key, and provide the corresponding APK signed with it? Thanks in advance!

**Comment by IzzySoft** [comment]
@ThisIsMatin @ItIsAlireza any word?

**Comment by ItIsAlireza** [comment]
Thanks for committing the issue 
We surely will fix that problem and release the app the way it must be.
And cause the app is a bit old(around 4yrs) we may even release a whole another app which does the same purpose but better and more modern with a better UI💙

**Comment by IzzySoft** [comment]
Thanks @ItIsAlireza! Any ETA for either (no pressure, just for orientation here)?

**Comment by ItIsAlireza** [comment]
We are a bit busy I'll do my best to deliver it ASAP
tomorrow I hope:)

**Comment by IzzySoft** [comment]
Time's running out @ItIsAlireza – I started purging the apps still having only debugkey-signed releases. I'll move yours to the end of the queue, but it would be good if the properly signed APK would be available in a week as by then I'll most likely have reached the end of the queue.

**Comment by ItIsAlireza** [comment]
Idk about the time running out, but I know when I'm busy I have to prioritize stuff. Anyway I get to it now

**Comment by ItIsAlireza** [comment]
Please check the release APK.

**Comment by IzzySoft** [comment]
Thanks a lot! That looks fine. Have replaced it here and pinned the new cert (i.e. only APKs signed with that key will be accepted as updates).

Just gave the APK a manual scan (my scanner got some additional checks since your app was first included):

```
No offending libs found.


Dangerous flags:
----------------
* usesCleartextTraffic

Permissions:
------------
* android.permission.INTERNET

SigningBlock blobs:
-------------------
0x504b4453 (DEPENDENCY_INFO_BLOCK; GOOGLE)
```

`usesCleartextTraffic` I've added to the app's "allow list" as it's needed to access resources in the local network (it's usuallly a warning about unencrypted traffic, but needed for things like this). `INTERNET` is clear as well. `DEPENDENCY_INFO_BLOCK` can easily be avoided:

```gradle
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

For some background: that BLOB is supposed to be just a binary representation of your app's dependency tree. But as it's encrypted with a public key belonging to Google, only Google can read it – and nobody else can even verify what it really contains.

It's currently on "info" level here, so no rush with that one. Just thought to mention it once I'm here, so you can put it "somewhere on your list". Once all the other things are tackled I might address those "signature blobs" here as well, but in the worst case they'll raise a warning here then "for transparency".

![image](https://github.com/AioFall/RhythmRoid/assets/6781438/f8d9a916-bc82-450e-94d4-77abd5e97078)

So thanks again for your help! I'll leave the issue open should you want to use it for `DEPENDENCY_INFO_BLOCK`, feel free to close :wink:

**Comment by ItIsAlireza** [comment]
Happy it was fixed, thanks for your concern
